#include "server.hpp"
#include <QDateTime>
#include <QJsonArray>
#include <QJsonDocument>
#include <QRandomGenerator>
#include <QTcpSocket>
#include <QTimer>
#include <cstring>
#include <QNetworkInterface>

namespace openbiounlock {
namespace { QJsonObject errorResponse(const QString &message) { return {{QStringLiteral("type"), QStringLiteral("error")}, {QStringLiteral("message"), message}}; } }
namespace { QByteArray timestampBytes(qint64 timestamp) { QByteArray result; for (int shift = 7; shift >= 0; --shift) result.append(char((timestamp >> (shift * 8)) & 0xff)); return result; } }
Server::Server(QObject *parent) : QObject(parent), pcId_(QByteArray::number(QRandomGenerator::global()->generate64(), 16)), x25519KeyPair_(crypto::generateX25519KeyPair()) { connect(&tcpServer_, &QTcpServer::newConnection, this, &Server::acceptConnections); connect(&udpSocket_, &QUdpSocket::readyRead, this, &Server::readDatagrams); }
bool Server::start(quint16 port) {
    if (isRunning()) return true; port_ = port;
    if (x25519KeyPair_.publicKey.size() != 32) { emit logMessage(QStringLiteral("X25519 key initialization failed")); return false; }
    pairingCode_ = QString::number(QRandomGenerator::global()->generate64(), 16).rightJustified(16, QLatin1Char('0'));
    pairingCreatedAt_ = QDateTime::currentSecsSinceEpoch();
    if (!tcpServer_.listen(QHostAddress::LocalHost, port_)) { emit logMessage(QStringLiteral("TCP listener failed: %1").arg(tcpServer_.errorString())); return false; }
    if (!udpSocket_.bind(QHostAddress::AnyIPv4, port_, QUdpSocket::ShareAddress | QUdpSocket::ReuseAddressHint)) { emit logMessage(QStringLiteral("UDP discovery listener failed: %1").arg(udpSocket_.errorString())); tcpServer_.close(); return false; }
    discoveryTimer_ = new QTimer(this); discoveryTimer_->setInterval(5000); connect(discoveryTimer_, &QTimer::timeout, this, &Server::broadcastDiscovery); discoveryTimer_->start(); broadcastDiscovery(); emit statusChanged(QStringLiteral("Listening on TCP/UDP %1").arg(port_)); emit logMessage(QStringLiteral("server started on port %1").arg(port_)); return true;
}
void Server::stop() { if (discoveryTimer_) { discoveryTimer_->stop(); discoveryTimer_->deleteLater(); discoveryTimer_ = nullptr; } for (QTcpSocket *socket : buffers_.keys()) socket->disconnectFromHost(); buffers_.clear(); tcpServer_.close(); udpSocket_.close(); emit statusChanged(QStringLiteral("Stopped")); }
bool Server::isRunning() const { return tcpServer_.isListening(); }
quint16 Server::port() const { return port_; }
QByteArray Server::pairingPayload(const QString &host) { QString endpoint = host; if (endpoint.isEmpty()) for (const QHostAddress &address : QNetworkInterface::allAddresses()) if (address.protocol() == QAbstractSocket::IPv4Protocol && !address.isLoopback() && !address.isMulticast()) { endpoint = address.toString(); break; } if (endpoint.isEmpty()) endpoint = QStringLiteral("127.0.0.1"); if (pairingCode_.isEmpty() || QDateTime::currentSecsSinceEpoch() - pairingCreatedAt_ > 300) { pairingCode_ = QString::number(QRandomGenerator::global()->generate64(), 16).rightJustified(16, QLatin1Char('0')); pairingCreatedAt_ = QDateTime::currentSecsSinceEpoch(); } const QJsonObject payload{{QStringLiteral("version"), 1}, {QStringLiteral("host"), endpoint}, {QStringLiteral("port"), port_}, {QStringLiteral("pc_id"), QString::fromLatin1(pcId_.toHex())}, {QStringLiteral("x25519_public_key"), QString::fromLatin1(x25519KeyPair_.publicKey.toHex())}, {QStringLiteral("pairing_code"), pairingCode_}}; return QJsonDocument(payload).toJson(QJsonDocument::Compact); }
void Server::acceptConnections() { while (QTcpSocket *socket = tcpServer_.nextPendingConnection()) { buffers_.insert(socket, {}); connect(socket, &QTcpSocket::readyRead, this, &Server::readClient); connect(socket, &QTcpSocket::disconnected, this, &Server::clientDisconnected); emit logMessage(QStringLiteral("client connected from %1").arg(socket->peerAddress().toString())); } }
void Server::readClient() { auto *socket = qobject_cast<QTcpSocket *>(sender()); if (!socket) return; QByteArray &buffer = buffers_[socket]; buffer += socket->readAll(); int end = -1; while ((end = buffer.indexOf('\n')) >= 0) { const QByteArray line = buffer.left(end).trimmed(); buffer.remove(0, end + 1); if (!line.isEmpty()) processLine(socket, line); } }
void Server::clientDisconnected() { auto *socket = qobject_cast<QTcpSocket *>(sender()); if (!socket) return; buffers_.remove(socket); emit logMessage(QStringLiteral("client disconnected")); socket->deleteLater(); }
void Server::processLine(QTcpSocket *socket, const QByteArray &line) {
    QJsonParseError parseError{}; const QJsonDocument document = QJsonDocument::fromJson(line, &parseError); if (parseError.error != QJsonParseError::NoError || !document.isObject()) { socket->write(QJsonDocument(errorResponse(QStringLiteral("invalid JSON request"))).toJson(QJsonDocument::Compact) + '\n'); return; }
    const QJsonObject request = document.object(); const QString requestType = request.value(QStringLiteral("type")).toString(); QJsonObject response;
    if (requestType == QStringLiteral("pair")) {
        const QString id = request.value(QStringLiteral("device_id")).toString(); const QByteArray signingKey = QByteArray::fromHex(request.value(QStringLiteral("public_key")).toString().toLatin1()); const QByteArray deviceKey = QByteArray::fromHex(request.value(QStringLiteral("x25519_public_key")).toString().toLatin1()); const QString code = request.value(QStringLiteral("pairing_code")).toString();
        if (id.isEmpty() || signingKey.size() != 32 || deviceKey.size() != 32 || code != pairingCode_ || QDateTime::currentSecsSinceEpoch() - pairingCreatedAt_ > 300) response = errorResponse(QStringLiteral("pairing code, keys, or pairing window is invalid"));
        else { QString error; const QByteArray shared = crypto::x25519SharedSecret(x25519KeyPair_.privateKey, deviceKey, &error); if (shared.size() != 32) response = errorResponse(error); else { pairedKeys_[id] = signingKey; sessionKeys_[id] = shared; pairingCode_.clear(); emit deviceChanged(id, true); response = {{QStringLiteral("type"), QStringLiteral("paired")}, {QStringLiteral("accepted"), true}, {QStringLiteral("pc_id"), QString::fromLatin1(pcId_.toHex())}}; emit logMessage(QStringLiteral("paired device %1").arg(id)); } }
    } else {
        QString deviceId; QJsonObject decrypted; QString error;
        if (!decryptRequest(request, &deviceId, &decrypted, &error)) response = errorResponse(error);
        else if (decrypted.value(QStringLiteral("type")).toString() == QStringLiteral("challenge")) { QByteArray nonce(32, Qt::Uninitialized); for (int offset = 0; offset < nonce.size(); offset += 8) { const quint64 value = QRandomGenerator::global()->generate64(); memcpy(nonce.data() + offset, &value, sizeof(value)); } const qint64 timestamp = QDateTime::currentSecsSinceEpoch(); response = encryptedResponse(deviceId, {{QStringLiteral("type"), QStringLiteral("challenge")}, {QStringLiteral("challenge_id"), QString::fromLatin1(nonce.toHex())}, {QStringLiteral("nonce"), QString::fromLatin1(nonce.toHex())}, {QStringLiteral("timestamp"), timestamp}}); }
        else if (decrypted.value(QStringLiteral("type")).toString() == QStringLiteral("verify")) { const QByteArray nonce = QByteArray::fromHex(decrypted.value(QStringLiteral("nonce")).toString().toLatin1()); const qint64 timestamp = decrypted.value(QStringLiteral("timestamp")).toVariant().toLongLong(); const QByteArray signature = QByteArray::fromHex(decrypted.value(QStringLiteral("signature")).toString().toLatin1()); QString verifyError; const bool authorized = pairedKeys_.contains(deviceId) && replayGuard_.accept(nonce, timestamp) && crypto::verifyEd25519(pairedKeys_.value(deviceId), nonce + timestampBytes(timestamp), signature, &verifyError); response = encryptedResponse(deviceId, {{QStringLiteral("type"), QStringLiteral("authorized")}, {QStringLiteral("authorized"), authorized}}); emit logMessage(authorized ? QStringLiteral("device %1 authorized").arg(deviceId) : QStringLiteral("authorization rejected: %1").arg(verifyError)); }
        else response = encryptedResponse(deviceId, errorResponse(QStringLiteral("unsupported request type")));
    }
    socket->write(QJsonDocument(response).toJson(QJsonDocument::Compact) + '\n');
}
QJsonObject Server::encryptedResponse(const QString &deviceId, const QJsonObject &payload) { QByteArray nonce(12, Qt::Uninitialized); for (int offset = 0; offset < nonce.size(); offset += 8) { const quint64 value = QRandomGenerator::global()->generate64(); memcpy(nonce.data() + offset, &value, qMin(8, nonce.size() - offset)); } QString error; const crypto::GcmCiphertext encrypted = crypto::encryptAes256Gcm(sessionKeys_.value(deviceId), nonce, QJsonDocument(payload).toJson(QJsonDocument::Compact), deviceId.toUtf8(), &error); if (encrypted.tag.size() != 16) return errorResponse(error); return {{QStringLiteral("type"), QStringLiteral("secure")}, {QStringLiteral("device_id"), deviceId}, {QStringLiteral("nonce"), QString::fromLatin1(nonce.toHex())}, {QStringLiteral("ciphertext"), QString::fromLatin1(encrypted.ciphertext.toHex())}, {QStringLiteral("tag"), QString::fromLatin1(encrypted.tag.toHex())}}; }
bool Server::decryptRequest(const QJsonObject &envelope, QString *deviceId, QJsonObject *payload, QString *error) { if (envelope.value(QStringLiteral("type")).toString() != QStringLiteral("secure")) { if (error) *error = QStringLiteral("unencrypted requests are not accepted"); return false; } const QString id = envelope.value(QStringLiteral("device_id")).toString(); if (!sessionKeys_.contains(id)) { if (error) *error = QStringLiteral("device is not paired"); return false; } const QByteArray nonce = QByteArray::fromHex(envelope.value(QStringLiteral("nonce")).toString().toLatin1()); const crypto::GcmCiphertext encrypted{QByteArray::fromHex(envelope.value(QStringLiteral("ciphertext")).toString().toLatin1()), QByteArray::fromHex(envelope.value(QStringLiteral("tag")).toString().toLatin1())}; QString localError; const QByteArray plaintext = crypto::decryptAes256Gcm(sessionKeys_.value(id), nonce, encrypted, id.toUtf8(), &localError); if (plaintext.isEmpty()) { if (error) *error = localError; return false; } QJsonParseError parseError{}; const QJsonDocument document = QJsonDocument::fromJson(plaintext, &parseError); if (parseError.error != QJsonParseError::NoError || !document.isObject()) { if (error) *error = QStringLiteral("decrypted payload is invalid"); return false; } *deviceId = id; *payload = document.object(); return true; }
void Server::readDatagrams() { while (udpSocket_.hasPendingDatagrams()) { QByteArray datagram; datagram.resize(int(udpSocket_.pendingDatagramSize())); QHostAddress address; quint16 port; udpSocket_.readDatagram(datagram.data(), datagram.size(), &address, &port); Q_UNUSED(port); QJsonParseError error{}; const QJsonDocument document = QJsonDocument::fromJson(datagram, &error); if (error.error == QJsonParseError::NoError && document.object().value(QStringLiteral("type")).toString() == QStringLiteral("discover")) broadcastDiscovery(); } }
void Server::broadcastDiscovery() { const QJsonObject packet{{QStringLiteral("type"), QStringLiteral("openbiounlock"), {QStringLiteral("pc_id"), QString::fromLatin1(pcId_.toHex())}, {QStringLiteral("port"), port_}}; const QByteArray data = QJsonDocument(packet).toJson(QJsonDocument::Compact); udpSocket_.writeDatagram(data, QHostAddress::Broadcast, port_); }
}